In [21]:
import numpy as np
import glob
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [22]:
facial_keypoints = pd.read_csv('P1.csv')
facial_labels = pd.read_csv("C:\\MITT\Labels\\turker_scores_full_interview.csv")

In [23]:
# CLEAN THE LABELS DATAFRAME FOR VIDEO ANALYSIS

# KEEPING ONLY AVG OF EACH PARTICIPANT
facial_labels = facial_labels[facial_labels['Worker'] == 'AGGR']
facial_labels.head()

,Participant,Worker,Overall,RecommendHiring,Colleague,Engaged,Excited,EyeContact,Smiled,SpeakingRate,...,Friendly,Paused,EngagingTone,StructuredAnswers,Calm,NotStressed,Focused,Authentic,NotAwkward,Total
9,p1,AGGR,5.297316,5.106224,5.333004,5.541380,5.043890,5.866119,3.576160,4.865590,...,5.254784,5.800468,5.147909,4.891580,5.351075,5.350760,5.845226,5.610513,5.477534,93.131196
19,p3,AGGR,4.414892,4.433070,5.010430,5.616076,5.601586,5.426861,6.062173,5.016286,...,6.500329,4.791550,5.621231,3.912199,4.476537,5.521215,5.549829,6.014960,4.923550,92.225232
29,p4,AGGR,4.494494,4.530129,4.500707,5.494494,4.261343,3.857848,4.852150,4.738000,...,5.369884,5.177447,4.392736,4.688379,5.065190,5.566084,5.324136,5.658364,4.452909,85.535740
39,p5,AGGR,5.457670,5.571558,5.772488,5.903057,4.707062,6.694276,3.920479,4.927181,...,5.649119,5.886326,4.695523,5.582514,6.130488,5.916373,6.322086,6.020070,5.629838,100.667850
49,p6,AGGR,5.106512,4.831482,4.860595,5.020385,4.648259,4.331805,4.194227,4.174891,...,4.495375,5.027823,4.261988,4.826245,5.828977,5.824390,5.619420,5.371858,5.295977,87.640538

In [24]:
facial_keypoints.head()

,frame,face_id,timestamp,confidence,success,x_0,x_1,x_2,x_3,x_4,...,AU12_c,AU14_c,AU15_c,AU17_c,AU20_c,AU23_c,AU25_c,AU26_c,AU28_c,AU45_c
0,1,0,0.000,0.88,1,300.9,300.5,300.9,301.5,302.7,...,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
1,2,0,0.034,0.88,1,300.6,300.2,300.6,301.3,302.5,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,3,0,0.069,0.88,1,300.4,300.1,300.5,301.2,302.4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,4,0,0.103,0.88,1,300.2,299.9,300.3,301.1,302.3,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,5,0,0.138,0.88,1,300.2,299.9,300.4,301.2,302.4,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [27]:
# KEEPING THE VIDEO LABELS 
video_labels = facial_labels.drop(['Colleague'], axis=1)
video_labels = facial_labels.iloc[:,[0, 5, 7,8, 11, 16, 17, 18, 19]].copy()
video_labels.head()

,Participant,Engaged,EyeContact,Smiled,Friendly,NotStressed,Focused,Authentic,NotAwkward
9,p1,5.541380,5.866119,3.576160,5.254784,5.350760,5.845226,5.610513,5.477534
19,p3,5.616076,5.426861,6.062173,6.500329,5.521215,5.549829,6.014960,4.923550
29,p4,5.494494,3.857848,4.852150,5.369884,5.566084,5.324136,5.658364,4.452909
39,p5,5.903057,6.694276,3.920479,5.649119,5.916373,6.322086,6.020070,5.629838
49,p6,5.020385,4.331805,4.194227,4.495375,5.824390,5.619420,5.371858,5.295977

In [28]:
# KEEPING THE AUDIO LABELS
Audio_labels = facial_labels.iloc[:,[0, 6, 9, 10, 12, 13, 14, 15]].copy()
Audio_labels.head()

,Participant,Excited,SpeakingRate,NoFillers,Paused,EngagingTone,StructuredAnswers,Calm
9,p1,5.043890,4.865590,3.771665,5.800468,5.147909,4.891580,5.351075
19,p3,5.601586,5.016286,3.332458,4.791550,5.621231,3.912199,4.476537
29,p4,4.261343,4.738000,3.111445,5.177447,4.392736,4.688379,5.065190
39,p5,4.707062,4.927181,5.881741,5.886326,4.695523,5.582514,6.130488
49,p6,4.648259,4.174891,3.920329,5.027823,4.261988,4.826245,5.828977

In [29]:
csv_files = glob.glob('*.csv')


data_frames = {}

for x in csv_files:
    print(x)

for file in csv_files:
    file_name = file.split('.')[0]
    data_frames[file_name] = pd.read_csv(file)

P1.csv
P10.csv
P11.csv
P12.csv
P13.csv
P14.csv
P15.csv
P16.csv
P17.csv
P20.csv
P21.csv
P22.csv
P24.csv
P25.csv
P27.csv
P29.csv
P3.csv
P30.csv
P31.csv
P32.csv
P33.csv
P34.csv
P35.csv
P37.csv
P4.csv
P42.csv
P43.csv
P44.csv
P45.csv
P47.csv
P48.csv
P49.csv
P5.csv
P50.csv
P52.csv
P53.csv
P55.csv
P56.csv
P57.csv
P58.csv
P6.csv
P7.csv
P8.csv

In [23]:
facial_keypoints.shape

(5713, 176)

In [30]:
# REMOVE THE FRAMES WHERE CONFIDENCE OF KEYPOINTS IS LESS THAN 0.85
def conficence_filter(df):
    df = df[df[' confidence'] >= .85].copy()
    return df

In [31]:
# TAKE ONLY POINTS WHERE MODEL WAS ABLE TO SUCCESSFULLY DETECT KEYPOINTS
def success_filter(df):
    df = df[df[' success'] == 1].copy()
    return df

In [32]:
def framesloss(df):
    df = df[df[' timestamp'] % 0.5 == 0].copy()
    return df

In [33]:
def remove_unwanted_columns(df):
    df = df.drop([' confidence'], axis=1)
    df = df.drop([' success'], axis=1)
    df = df.drop([' face_id'], axis=1)
    df = df.drop(['frame'], axis=1)
    return df

def remove_AUs(df):
    df = df.drop([' AU01_r'], axis=1)
    df = df.drop([' AU02_r'], axis=1)
    df = df.drop([' AU04_r'], axis=1)
    df = df.drop([' AU05_r'], axis=1)
    df = df.drop([' AU06_r'], axis=1)
    df = df.drop([' AU07_r'], axis=1)
    df = df.drop([' AU09_r'], axis=1)
    df = df.drop([' AU10_r'], axis=1)
    df = df.drop([' AU12_r'], axis=1)
    df = df.drop([' AU14_r'], axis=1)
    df = df.drop([' AU15_r'], axis=1)
    df = df.drop([' AU17_r'], axis=1)
    df = df.drop([' AU20_r'], axis=1)
    df = df.drop([' AU23_r'], axis=1)
    df = df.drop([' AU25_r'], axis=1)
    df = df.drop([' AU26_r'], axis=1)
    df = df.drop([' AU45_r'], axis=1)
    df = df.drop([' AU01_c'], axis=1)
    df = df.drop([' AU02_c'], axis=1)
    df = df.drop([' AU04_c'], axis=1)
    df = df.drop([' AU05_c'], axis=1)
    df = df.drop([' AU06_c'], axis=1)
    df = df.drop([' AU07_c'], axis=1)
    df = df.drop([' AU09_c'], axis=1)
    df = df.drop([' AU10_c'], axis=1)
    df = df.drop([' AU12_c'], axis=1)
    df = df.drop([' AU14_c'], axis=1)
    df = df.drop([' AU15_c'], axis=1)
    df = df.drop([' AU17_c'], axis=1)
    df = df.drop([' AU20_c'], axis=1)
    df = df.drop([' AU23_c'], axis=1)
    df = df.drop([' AU25_c'], axis=1)
    df = df.drop([' AU26_c'], axis=1)
    df = df.drop([' AU28_c'], axis=1)
    df = df.drop([' AU45_c'], axis=1)
    return df

# FACIAL KEY POINTS ARE 1 UNITS AHEAD IN THIS SEQUENCE FOR X 
# def remove_unwanted_coordinates(df):
#     # 18-49 X
#     df = df.iloc[:, [18, 22, 37, 40, 45, 47, 39, 41, 51, 52, 53, 59, 58, 57, 62, 63, 64, 68, 67, 66, 55, 49, 68]].copy()
#     return df


def remove_unwanted_coordinates(df):
    df = df.loc[:, [' x_17', ' x_36', ' x_21', ' x_39', ' x_44', ' x_46', ' x_38', ' x_40', ' x_50', ' x_58', ' x_51', ' x_57',
                    ' x_52', ' x_56', ' x_61', ' x_62', ' x_63', ' x_67', ' x_66', ' x_65', ' x_54', ' x_48',
                    ' y_17', ' y_36', ' y_21', ' y_39', ' y_44', ' y_46', ' y_38', ' y_40', ' y_50', ' y_58', ' y_51', ' y_57',
                    ' y_52', ' y_56', ' y_61', ' y_62', ' y_63', ' y_67', ' y_66', ' y_65', ' y_54', ' y_48']].copy()
    return df

In [34]:
# ECULIDEAN DISTANCE


# CALCULATING THE OUTER BROW HEIGHT

def calculate_OBH(df):
    df['OBH'] = ((df[' x_36'] - df[' x_17'])**2 + (df[' y_36'] - df[' y_17'])**2)**0.5
    return df


# CALCULATING THE INNER BROW HEIGHT
def calculate_IBH(df):
    df['IBH'] = ((df[' x_39'] - df[' x_21'])**2 + (df[' y_39'] - df[' y_21'])**2)**0.5
    return df

# CALCULATING THE LEFT EYE OPEN
def calculate_LEO(df):
    df['LEO'] = ((df[' x_46'] - df[' x_44'])**2 + (df[' y_46'] - df[' y_44'])**2)**0.5
    return df

# CALCULATING THE RIGHT EYE OPEN
def calculate_REO(df):
    df['REO'] = ((df[' x_40'] - df[' x_38'])**2 + (df[' y_40'] - df[' y_38'])**2)**0.5
    return df

# CALCULATING THE OUTER LIP HEIGHT
def calculate_OLH(df):
    # Calculate Euclidean distances for each set of data points
    d1 = ((df[' x_58'] - df[' x_50'])**2 + (df[' y_58'] - df[' y_50'])**2)**0.5
    d2 = ((df[' x_57'] - df[' x_51'])**2 + (df[' y_57'] - df[' y_51'])**2)**0.5
    d3 = ((df[' x_56'] - df[' x_52'])**2 + (df[' y_56'] - df[' y_52'])**2)**0.5

    # Take the average of the distances
    df['OLH'] = (d1+d2+d3) / 3
    return df


def calculate_ILH(df):
    # Calculate Euclidean distances for each set of data points
    d1 = ((df[' x_67'] - df[' x_61'])**2 + (df[' y_67'] - df[' y_61'])**2)**0.5
    d2 = ((df[' x_66'] - df[' x_62'])**2 + (df[' y_66'] - df[' y_62'])**2)**0.5
    d3 = ((df[' x_65'] - df[' x_63'])**2 + (df[' y_65'] - df[' y_63'])**2)**0.5

    # Take the average of the distances
    df['ILH'] = (d1+d2+d3) / 3
    return df


def smile(df):
    df['smile'] = ((df[' x_48'] - df[' x_54'])**2 + (df[' y_48'] - df[' y_54'])**2)**0.5
    return df

In [35]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()


processed_dataframes = []


for file_name, dataframe in data_frames.items():
    # print(f"File Name: {file_name}")

    # CLEARENCE
    dataframe = framesloss(dataframe)
    dataframe = success_filter(dataframe)
    dataframe =  conficence_filter(dataframe)
    dataframe = remove_unwanted_columns(dataframe)
    dataframe = remove_AUs(dataframe)
    dataframe = remove_unwanted_coordinates(dataframe)

    # CALCULATING THE FEATURES
    
    dataframe = calculate_OBH(dataframe)
    dataframe = calculate_IBH(dataframe)
    dataframe = calculate_LEO(dataframe)
    dataframe = calculate_REO(dataframe)
    dataframe = calculate_OLH(dataframe)
    dataframe = calculate_ILH(dataframe)
    dataframe = smile(dataframe)

    dataframe = dataframe.loc[:, ['OBH', 'IBH', 'LEO', 'REO', 'OLH', 'ILH', 'smile']].copy()
    dataframe = scaler.fit_transform(dataframe)
    dataframe = pd.DataFrame(dataframe, columns=['OBH', 'IBH', 'LEO', 'REO', 'OLH', 'ILH', 'smile'])
    dataframe.insert(0, 'Participant', file_name.lower())
    
    dataframe = pd.merge(dataframe, video_labels, on='Participant', how='left')
    processed_dataframes.append(dataframe)

    # Display the final merged dataframe
    # print(dataframe)
 # Display the first few rows of the DataFrame
    # print("\n")  # Add a newline for better readability

merged_dataframe = pd.concat(processed_dataframes, ignore_index=True)

In [36]:
merged_dataframe.head()

,Participant,OBH,IBH,LEO,REO,OLH,ILH,smile,Engaged,EyeContact,Smiled,Friendly,NotStressed,Focused,Authentic,NotAwkward
0,p1,0.047550,0.169749,0.063835,0.094563,0.295091,0.374149,0.083074,5.54138,5.866119,3.57616,5.254784,5.35076,5.845226,5.610513,5.477534
1,p1,0.000000,0.027915,0.063835,0.010951,0.122328,0.121078,0.009353,5.54138,5.866119,3.57616,5.254784,5.35076,5.845226,5.610513,5.477534
2,p1,0.057608,0.102733,0.031917,0.014570,0.180096,0.245066,0.041152,5.54138,5.866119,3.57616,5.254784,5.35076,5.845226,5.610513,5.477534
3,p1,0.043374,0.048576,0.000000,0.019611,0.127547,0.187659,0.043110,5.54138,5.866119,3.57616,5.254784,5.35076,5.845226,5.610513,5.477534
4,p1,0.018077,0.018526,0.063221,0.060279,0.146883,0.207027,0.059127,5.54138,5.866119,3.57616,5.254784,5.35076,5.845226,5.610513,5.477534

In [37]:
merged_dataframe = merged_dataframe.drop('Participant', axis=1)
merged_dataframe.head()

,OBH,IBH,LEO,REO,OLH,ILH,smile,Engaged,EyeContact,Smiled,Friendly,NotStressed,Focused,Authentic,NotAwkward
0,0.047550,0.169749,0.063835,0.094563,0.295091,0.374149,0.083074,5.54138,5.866119,3.57616,5.254784,5.35076,5.845226,5.610513,5.477534
1,0.000000,0.027915,0.063835,0.010951,0.122328,0.121078,0.009353,5.54138,5.866119,3.57616,5.254784,5.35076,5.845226,5.610513,5.477534
2,0.057608,0.102733,0.031917,0.014570,0.180096,0.245066,0.041152,5.54138,5.866119,3.57616,5.254784,5.35076,5.845226,5.610513,5.477534
3,0.043374,0.048576,0.000000,0.019611,0.127547,0.187659,0.043110,5.54138,5.866119,3.57616,5.254784,5.35076,5.845226,5.610513,5.477534
4,0.018077,0.018526,0.063221,0.060279,0.146883,0.207027,0.059127,5.54138,5.866119,3.57616,5.254784,5.35076,5.845226,5.610513,5.477534

In [38]:
# Assuming merged_dataframe is your DataFrame
X = merged_dataframe.iloc[:, :7]
y = merged_dataframe.iloc[:, 7:]

print(X.shape)
print(y.shape)

(13420, 7)
(13420, 8)

## SVR

In [58]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from joblib import dump, load

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


svr_model = SVR(kernel='linear', C=1.0)
multi_output_model = MultiOutputRegressor(svr_model)
multi_output_model.fit(X_train, y_train)

dump(multi_output_model, 'svr_model.joblib')
y_pred = multi_output_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)
acc =  mse+30 # svr_model = SVR(kernel='linear', C=1.0)
# multi_output_model = MultiOutputRegressor(svr_model)
# multi_output_model.fit(X_train, y_train)

# Display the results
print(f"Mean Squared Error: {mse}")

Mean Squared Error: 0.4064541266630856

In [60]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.multioutput import MultiOutputRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from joblib import dump, load

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


svr_model = SVR(kernel='poly', degrees =3, C=1.0)
multi_output_model = MultiOutputRegressor(svr_model)
multi_output_model.fit(X_train, y_train)

dump(multi_output_model, 'svr_model.joblib')
y_pred = multi_output_model.predict(X_test)
mse = mean_squared_error(y_test, y_pred)

# Display the results
print(f"Mean Squared Error: {mse}")

## CNN

In [55]:
import numpy as np
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler



# Reshape X to 3D tensor (samples, time steps, features)
X_reshaped = X.values.reshape((X.shape[0], X.shape[1], 1))

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_reshaped, y, test_size=0.2, random_state=42)

# Standardize input features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train.reshape((X_train.shape[0], X_train.shape[1])))
X_test_scaled = scaler.transform(X_test.reshape((X_test.shape[0], X_test.shape[1])))

# Define the CNN model
model = Sequential()
model.add(Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(X_train_scaled.shape[1], 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(8, activation='softmax'))  # Adjust the number of units to match your number of classes


model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_scaled, y_train, epochs=10, batch_size=32, validation_data=(X_test_scaled, y_test))

Epoch 1/10
336/336 [==============================] - 2s 5ms/step - loss: 108.3870 - accuracy: 0.2479 - val_loss: 141.3616 - val_accuracy: 0.2511
Epoch 2/10
336/336 [==============================] - 2s 5ms/step - loss: 180.1580 - accuracy: 0.2566 - val_loss: 220.4906 - val_accuracy: 0.2537
Epoch 3/10
336/336 [==============================] - 1s 4ms/step - loss: 257.9361 - accuracy: 0.2551 - val_loss: 300.5811 - val_accuracy: 0.2504
Epoch 4/10
336/336 [==============================] - 2s 5ms/step - loss: 335.8681 - accuracy: 0.2515 - val_loss: 377.1898 - val_accuracy: 0.2500
Epoch 5/10
336/336 [==============================] - 2s 5ms/step - loss: 411.9542 - accuracy: 0.2491 - val_loss: 455.3014 - val_accuracy: 0.2522
Epoch 6/10
336/336 [==============================] - 2s 5ms/step - loss: 488.6387 - accuracy: 0.2490 - val_loss: 531.8201 - val_accuracy: 0.2485
Epoch 7/10
336/336 [==============================] - 2s 5ms/step - loss: 563.8224 - accuracy: 0.2488 - val_loss: 608.3482 - val_accuracy: 0.2481
Epoch 8/10
336/336 [==============================] - 2s 5ms/step - loss: 636.2531 - accuracy: 0.2473 - val_loss: 677.1130 - val_accuracy: 0.2440
Epoch 9/10
336/336 [==============================] - 2s 5ms/step - loss: 709.8130 - accuracy: 0.2474 - val_loss: 750.4333 - val_accuracy: 0.2470
Epoch 10/10
336/336 [==============================] - 2s 5ms/step - loss: 780.9017 - accuracy: 0.2465 - val_loss: 826.8842 - val_accuracy: 0.2478

In [48]:
y_pred = multi_output_model.predict(X_test)

# Evaluate the performance of the model (assuming regression)
mse = mean_squared_error(y_test, y_pred)
r_squared = r2_score(y_test, y_pred)

# Display the results
print(f"Mean Squared Error: {mse}")
print(f"R-squared: {r_squared}")

Mean Squared Error: 0.4064541266630856
R-squared: 0.05914140558474698

In [50]:
from keras.layers import Conv1D, MaxPooling1D, Flatten, Dropout

X_reshaped = X_array.reshape((X_array.shape[0], X_array.shape[1], 1))

# Define the CNN model
model = Sequential()
model.add(Conv1D(filters=32, kernel_size=3, activation='relu', input_shape=(X_array.shape[1], 1)))
model.add(MaxPooling1D(pool_size=2))
model.add(Flatten())
model.add(Dense(units=8, activation='softmax'))
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])


# Train the model
model.fit(X_train, Y_train, epochs=10, batch_size=32)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test, Y_test)
print(f"Loss: {loss}, Accuracy: {accuracy}")

Epoch 1/10
336/336 [==============================] - 4s 5ms/step - loss: 27.8089 - accuracy: 0.4069
Epoch 2/10
336/336 [==============================] - 2s 5ms/step - loss: 27.7992 - accuracy: 0.4824
Epoch 3/10
336/336 [==============================] - 1s 4ms/step - loss: 27.7987 - accuracy: 0.4820
Epoch 4/10
336/336 [==============================] - 1s 4ms/step - loss: 27.7984 - accuracy: 0.4820
Epoch 5/10
336/336 [==============================] - 2s 6ms/step - loss: 27.7982 - accuracy: 0.4818
Epoch 6/10
336/336 [==============================] - 2s 5ms/step - loss: 27.7979 - accuracy: 0.4821
Epoch 7/10
336/336 [==============================] - 2s 5ms/step - loss: 27.7979 - accuracy: 0.4820
Epoch 8/10
336/336 [==============================] - 2s 6ms/step - loss: 27.7977 - accuracy: 0.4823
Epoch 9/10
336/336 [==============================] - 2s 7ms/step - loss: 27.7976 - accuracy: 0.4828
Epoch 10/10
336/336 [==============================] - 3s 8ms/step - loss: 27.7975 - accuracy: 0.4824
84/84 [==============================] - 1s 6ms/step - loss: 27.8922 - accuracy: 0.4724
Loss: 27.892169952392578, Accuracy: 0.47242921590805054

## RNN

In [59]:
from keras.optimizers import Adam
from keras.callbacks import EarlyStopping, ReduceLROnPlateau
from keras.layers import Dropout

# Define the RNN model with dropout and regularization
model = Sequential()
model.add(SimpleRNN(units=128, input_shape=(X_scaled.shape[1], 1)))
model.add(Dropout(0.5))  # Add dropout layer
model.add(Dense(units=8, activation='softmax', kernel_regularizer='l2'))  # Add L2 regularization

# Compile the model with Adam optimizer and categorical_crossentropy loss
model.compile(optimizer=Adam(learning_rate=0.001), loss='categorical_crossentropy', metrics=['accuracy'])

# Implement early stopping and learning rate reduction
early_stopping = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)
reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.1, patience=3, min_lr=1e-6)

# Train the model with more epochs
model.fit(
    X_train, Y_train, 
    epochs=50, 
    batch_size=64, 
    validation_data=(X_test, Y_test),
    callbacks=[early_stopping, reduce_lr]
)

Epoch 1/50
168/168 [==============================] - 4s 15ms/step - loss: 147.7958 - accuracy: 0.0844 - val_loss: 127.2467 - val_accuracy: 0.0771 - lr: 0.0010
Epoch 2/50
168/168 [==============================] - 2s 12ms/step - loss: 154.2567 - accuracy: 0.0904 - val_loss: 127.4422 - val_accuracy: 0.0771 - lr: 0.0010
Epoch 3/50
168/168 [==============================] - 2s 15ms/step - loss: 155.0891 - accuracy: 0.0902 - val_loss: 128.8488 - val_accuracy: 0.0771 - lr: 0.0010
Epoch 4/50
168/168 [==============================] - 2s 12ms/step - loss: 156.7882 - accuracy: 0.0881 - val_loss: 130.9666 - val_accuracy: 0.0771 - lr: 0.0010
Epoch 5/50
168/168 [==============================] - 2s 12ms/step - loss: 157.7868 - accuracy: 0.0911 - val_loss: 131.1733 - val_accuracy: 0.0771 - lr: 1.0000e-04
Epoch 6/50
168/168 [==============================] - 2s 12ms/step - loss: 158.0249 - accuracy: 0.0854 - val_loss: 131.4665 - val_accuracy: 0.0771 - lr: 1.0000e-04